openapi: 3.0.3

info:
  title: Glider Insurance
  description: Multi-tenant bridge for insurance providers on Winding Tree marketplace
  contact:
    email: dev@windingtree.com
  license:
    name: GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: 1.0.0

servers:
  - url: API_VERSION_URL
    description: API server

tags:
  - name: offers
    description: Search for insurance policies offers
  - name: orders
    description: Creation of insurance orders
  - name: service
    description: API service functions

paths:
  /offers/search:
    post:
      tags:
        - offers
      summary: Offers Search
      operationId: offersSearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OffersSearchCriteria"
      security:
        - orgid_auth:
            - read:offers
            - write:offers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OffersSearchResults"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authorization required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        502:
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /orders:
    post:
      tags:
        - orders
      summary: Create an order
      operationId: ordersCreate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateBody"
      security:
        - orgid_auth:
            - read:offers
            - write:offers
            - write:orders
      responses:
        200:
          description: Order Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsuranceOrder"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authorization required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        502:
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /orders/{orderId}:
    get:
      tags:
        - orders
      summary: Get an order
      operationId: ordersGet
      parameters:
        - in: path
          name: orderId
          description: An order Id
          schema:
            $ref: "#/components/schemas/UUID"
      security:
        - orgid_auth:
            - read:orders
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsuranceOrder"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authorization required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        502:
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - orders
      summary: Emit an insurance contract
      operationId: ordersEmitContract
      parameters:
        - in: path
          name: orderId
          description: An order Id
          schema:
            $ref: "#/components/schemas/UUID"
      security:
        - orgid_auth:
            - read:orders
            - write:orders
      responses:
        200:
          description: Order Code Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContractEmitResult"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authorization required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        502:
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /service/ping:
    get:
      tags:
        - service
      summary: Ping-pong
      operationId: servicePing
      parameters:
        - in: query
          name: message
          description: Optional incoming message
          schema:
            type: string
          example: Ping
      security: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"

    post:
      tags:
        - service
      summary: Ping-pong using POST
      operationId: servicePingPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PingRequest"
      security: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"

components:
  schemas:
    OffersSearchCriteria:
      description: Insurance policies offers search criteria
      type: object
      required:
        - territory
        - period_from
        - period_till
        - tourists
        - target
        - currency
      properties:
        territory:
          description: Country Code
          $ref: "#/components/schemas/TerritoryCode"
        period_from:
          description: Insurance period start date
          $ref: "#/components/schemas/ShortDate"
        period_till:
          description: Insurance period end date
          $ref: "#/components/schemas/ShortDate"
        target:
          description: Type of Activities
          $ref: "#/components/schemas/ActivitiesType"
        citizenship:
          description: Citizenship
          type: string
          example: Ukraine
        currency:
          description: Insurance price currency
          $ref: "#/components/schemas/Currency"
          enum:
            - EUR
            - USD
        tourists:
          description: List of tourists
          type: array
          items:
            $ref: "#/components/schemas/Tourist"
          uniqueItems: true

    OrderCreateBody:
      description: Order creation criteria
      type: object
      required:
        - offerId
        - guaranteeId
        - insurer
      properties:
        offerId:
          description: Offer Id
          $ref: "#/components/schemas/UUID"
        guaranteeId:
          description: Payment guarantee Id
          $ref: "#/components/schemas/UUID"
        insurer:
          description: Insurer Tourist Id
          type: string
          example: PAX1

    OffersSearchResults:
      description: Array of offers
      type: object
      properties:
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"

    Offer:
      description: Insurance policy offer
      type: object
      required:
        - offerId
        - expiration
        - id
        - cost
        - name
        - desc
        - currency
      properties:
        offerId:
          description: Offer Id
          $ref: "#/components/schemas/UUID"
        expiration:
          description: The offer expiration time
          type: string
          format: date-time
          example: "2021-04-12T23:20:50.52Z"
        id:
          description: Program Id
          $ref: "#/components/schemas/InsuranceProgramId"
          example: sub_standart_vzr
        cost:
          description: Insurance payment
          type: number
          example: 234.72
        code:
          description: Internal ID of the tariff condition
          type: number
          example: 4
        name:
          description: The name of tariff
          type: string
          example: Standard
        desc:
          description: The description of tariff
          type: string
          example: Standard
        currency:
          description: Currency in which currency is valued
          $ref: "#/components/schemas/Currency"
        covid_inc:
          description: Is COVID case included into the insurance
          type: boolean
          example: true
        tourists:
          description: A list of tourists Ids
          type: array
          items:
            $ref: "#/components/schemas/TouristId"

    InsuranceOrder:
      description: Insurance Order
      type: object
      required:
        - orderId
        - offerId
        - id
        - number
        - cost
        - currency
      properties:
        orderId:
          description: The Order Id
          $ref: "#/components/schemas/UUID"
        offerId:
          description: Confirmed Offer Id
          $ref: "#/components/schemas/UUID"
        id:
          description: The contract Identifier
          type: number
          example: 123
        number:
          description: The contract number is indicated in PDF
          type: number
          example: 1222
        cost:
          description: Insurance payment
          type: number
          example: 234.72
        currency:
          description: Currency of the insurance payment
          $ref: "#/components/schemas/Currency"
        issued:
          description: An insurance contract issuance indicator
          type: boolean
          example: false
        issuanceDate:
          description: A data of the contract issuance
          type: string
          format: date-time
          example: "2021-04-14T23:20:50.52Z"
        pdfUrl:
          description: A link to the contract PDF file
          $ref: "#/components/schemas/PdfUrl"

    ContractEmitResult:
      description: An order signing code
      type: object
      required:
        - pdfUrl
      properties:
        pdfUrl:
          description: The contract PDF URL
          $ref: "#/components/schemas/PdfUrl"

    PdfUrl:
      description: The contract PDF URL
      type: string
      format: url
      example: https://api.ic-ekta.com/travel/download/123

    InsuranceType:
      description: Type of Insurance
      type: string
      enum:
        - single # Single trip
      example: single

    TerritoryCode:
      description: Territory Code
      type: string
      enum:
        - europe
        - schengen
        - cis
        - global
      example: global

    InsuranceLimit:
      description: Sum insured
      type: number
      enum:
        - 3000
        - 30000
        - 50000
      example: 30000

    ActivitiesType:
      description: Type of Activities
      type: string
      enum:
        - sport
        - tourism
        - work
      example: tourism

    DescriptionLanguage:
      description: The language on which to return the name and description of tariff
      type: string
      enum:
        - ru # Russian
        - ua # Ukrainian
        - en # English
      example: en

    InsuranceProgramId:
      description: The name of the program
      type: string
      enum:
        - cpa_vzr_basic    # 3000 EUR
        - standart_vzr_sub # 3000 EUR
        - cpa_vzr_standart # 3000 EUR
        - sub_standart_vzr # 30000 EUR
        - sub_premium_vzr  # 50000 USD
        - cpa_vzr_premium  # 50000 USD

    Tourist:
      description: Tourist personal data
      type: object
      required:
        - id
        - name_first
        - name_last
        - phone
        - city
        - email
        - birthday
        - passport
      properties:
        id:
          description: The tourist Id
          $ref: "#/components/schemas/TouristId"
        name_first:
          description: First name
          type: string
          example: Petro
        name_last:
          description: Last name
          type: string
          example: Petrovsky
        phone:
          description: Phone number
          $ref: "#/components/schemas/PhoneNumber"
        city:
          description: City
          type: string
          example: Odesa
        address:
          description: Home address
          type: string
          example: Myasoedovskaya str.
        build:
          description: Home building number
          type: string
          example: 8
        email:
          description: Personal email
          $ref: "#/components/schemas/Email"
        birthday:
          description: Birthday
          $ref: "#/components/schemas/ShortDate"
        passport:
          description: passport
          type: string
          example: FE 123456

    Email:
      description: An email
      type: string
      pattern: '^.+?@.+\..+?$'
      example: contact@org.co.uk

    PhoneNumber:
      description: A phone number
      type: string
      pattern: '^\+[0-9]+$'
      example: "+32123456789"

    ShortDate:
      description: Date in format YYYY-mm-dd
      type: string
      format: date
      example: "2020-11-21"

    Currency:
      description: The ISO4217 currency code
      type: string
      pattern: "^[A-Z]{3}$"
      minLength: 3
      maxLength: 3
      example: EUR

    TouristId:
      description: Insurer Tourist Id
      type: string
      example: PAX1

    UUID:
      description: Unique identifier for Offers and Orders
      type: string
      format: uuid
      minLength: 36
      maxLength: 36
      pattern: "^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$"
      example: "11111111-2222-3333-4444-000000000001"

    Error:
      description: Object describing an error
      type: object
      required:
        - message
        - code
      properties:
        message:
          description: Error message
          type: string
          example: "Something went wrong"
        code:
          description: Error code
          type: string
          pattern: "^[0-9A-Z]+$"
          example: "BAD_REQUEST"

    PingRequest:
      description: Request options for Ping
      type: object
      required:
        - message
      properties:
        message:
          description: Request message
          type: string
          example: Ping

    Pong:
      description: Pong response object
      type: object
      required:
        - message
      properties:
        message:
          description: Response message
          type: string
          example: Pong
        date:
          description: Current server date
          type: string
          format: date-time
          example: "2021-04-14T23:20:50.52Z"

  securitySchemes:
    orgid_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
